version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack:/tmp/localstack"

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - ".:/workspace"
    working_dir: "/workspace"
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 2073600; done"]
